### ISSUE TITLE
Update About us page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#101]
Update map and people working on the project. We need to discuss collaboration logos.

**Comment by ReneRanzinger** [comment]
Map: 
* Remove Australian nodes, London node
* For US nodes we need to update them once they have finalized the list of advisors

People: 
* Move Will to former members
* Rename Advocates to Advisors 
* Request list of Advisors from Raja and Mike
* Former Members: remove pictures and just keep text
* Delete Tyler Stewart

Logos:
* Remove Harvard Univerity, Grifffith University, Imperial College London, Macqyarie University

**Comment by sujeetvkulkarni** [comment]
@jeet-vora

**Comment by sujeetvkulkarni** [comment]
efc637d4b969216f74dcf714824b80216efde487
