### ISSUE TITLE
N-Glycan Gnome Browser integration

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#103]
We need to add the new restrictions of GNOme browser as links to our "Related Glycan" button. This could be in a way that the button triggers a dropdown with the different options.

@edwardsnj Can provide the different options (see #32 )
@rykahsay May have to add information to the API that show or hide certain options.

**Comment by edwardsnj** [comment]
This comment lists the probably useful options (all are GlyGen specific / branded restrictions): https://github.com/glygener/glygen-frontend/issues/32#issuecomment-1337780121

**Comment by edwardsnj** [comment]
@rykahsay What is data-integration path for the list(s) of accessions that indicate whether an external link should be provided to a particular service? Do they get consumed as any other data-source (i.e. Sandbox?)

**Comment by ReneRanzinger** [comment]
Robel finished the tools integration in #167 .

**Comment by sujeetvkulkarni** [comment]
{
   "gnome_glygen_oglycans":"GlyGen O-Glycans",
   "gnome_glygen":"GlyGen Glycans",
   "gnome_glygen_nglycans":"GlyGen N-Glycans",
}

**Comment by sujeetvkulkarni** [comment]
efc637d4b969216f74dcf714824b80216efde487
