### ISSUE TITLE
3D structures for glycans

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#104]
Add a 3D structure viewer for Glygens into the Glycan details page. Options:

* Mol* as used by [PDB](https://www.rcsb.org/3d-view/1AOL/1)
* LiteMol as used by Glycam

**Comment by jeet-vora** [comment]
@sujeetvkulkarni @ReneRanzinger 
The path to glycam 3d glycan files is - https:/data.glygen.org/ln2downloads/glycam_3d/glycan/current/*.pdb

**Comment by ReneRanzinger** [comment]
Page that uses LiteMol:
https://glycosmos.org/glycans/show/G84596RP

**Comment by sujeetvkulkarni** [comment]
@jeet-vora

**Comment by sujeetvkulkarni** [comment]
> @sujeetvkulkarni @ReneRanzinger The path to glycam 3d glycan files is - https:/data.glygen.org/ln2downloads/glycam_3d/glycan/current/*.pdb

@jeet-vora @ReneRanzinger 
Why the file format is different from 
https://files.rcsb.org/view/4wrn.pdb
this file and 
our location
https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb
File content is different is ok but shouldn't the file format be same if both are pdb files?
Can you please give me original links of the https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb pdb files?
For 3D viewer I guess the files need to be in particular format.

**Comment by sujeetvkulkarni** [comment]
Also, for https://files.rcsb.org/view/4wrn.pdb 
content type is text/plain;charset=UTF-8
But for 
https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb
content type is application/x-pilot
which should be text/plain;charset=UTF-8

**Comment by sujeetvkulkarni** [comment]
[4wrn.pdb.txt](https://github.com/glygener/glygen-frontend/files/10511904/4wrn.pdb.txt)
[G17689DH.pdb.txt](https://github.com/glygener/glygen-frontend/files/10511913/G17689DH.pdb.txt)

Attaching both downloaded files comparison. I had to manually add .txt extension to "G17689DH.pdb" to upload on Github.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni They are not different. 4wrn.pdb has a lot of metadata in the begining (paper, aminoacid sequence etc.) The actual data starts with:
`ATOM      1  N   GLY A  18     -34.227  29.571  52.189  1.00151.08           N `
All the metadata in the header is optional.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger ok, I will check if 3D viewer needs some of the header part. But I guess the content type need change.
@jeet-vora It would be great if you could point me to original url for [G17689DH](https://github.com/glygener/glygen-frontend/files/10511913/G17689DH.pdb.txt). Also, if you could point me to an example from https://files.rcsb.org/view/4wrn.pdb which we host on [https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/](https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb) that would be great.

**Comment by sujeetvkulkarni** [comment]
@jeet-vora @ReneRanzinger 
I was able to load the downloaded pdb file from
https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb
into online molstar (https://molstar.org/viewer/) viewer so I dont think the header part is needed to load the pdb in 3D viewer.

**Comment by sujeetvkulkarni** [comment]
https://glycam.org/cb/download/
DNeup5Aca2-3DGalpb1-4DGlcpNAcb1-2DManpa1-3[DNeup5Aca2-3DGalpb1-4DGlcpNAcb1-2DManpa1-6]DManpb1-4DGlcpNAcb1-4[LFucpa1-6]DGlcpNAcb1-OH

**Comment by sujeetvkulkarni** [comment]
Opacity, Size of carbohydrates:
https://github.com/glygener/glygen-issues/issues/129
