### ISSUE TITLE
Glycan data update based on Glycan Workflow

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#107]
We will test the new glycan data workflow that @edwardsnj and @kmartinez834 agreed upon. And make a glycan update for 2.0

**Comment by kmartinez834** [comment]
Glycan data export [v1.12.0](https://github.com/glygen-glycan-data/PyGly/releases/tag/GlyGen-GlycanData-Export-v1.12.0) has been uploaded to the GlyGen server at downloads/glytoucan/current/export

Ready for processing.

**Comment by rykahsay** [comment]
@kmartinez834 --- I have updated all the glycan_* and *_proteoform_* datasets, please check
