### ISSUE TITLE
Deployment of data to AWS instance

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#110]

**Comment by rykahsay** [comment]
@rajamazumder @jeet-vora @kmartinez834 
Raja -- this is the relevant issue/ticket but I don't think Tianyi has access to this repo. 

One can clone the repo given below and follow instructions in the README.md.

https://github.com/glygener/glygen-backend-datasetviewer

**Comment by ReneRanzinger** [comment]
@rykahsay Repository and tickets are public. But if you want to assign the ticket or a tasks to Tianyi we should add as a member. Jeet or I can do if we have the github account.

**Comment by jeet-vora** [comment]
Primary assignee Tiyani.
@tiwa1154 Please track this ticket and link your ticket with this.

**Comment by tiwa1154** [comment]
@rajamazumder The date module has been installed on AWS but I don't have a domain. How do you want me to proceed with this? I would need a domain so I can show you the data installed on AWS. For example, GlyGen's current domain is data.glygen.org and I would need something similar to this to show the data.

**Comment by jeet-vora** [comment]
@Tianyi Wang ***@***.***> Have you talked about this with @Robel
Kahsay ***@***.***>? He will help you setup the domain if
needed.

**Comment by tiwa1154** [comment]
@jeet-vora Yes, I talked to Robel and he asked me to make sure with Raja if that's what he wants, referring to setting up a different domain to show the data module that was deployed on AWS.
