### ISSUE TITLE
Rajas paper issue

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#117]
@jeet-vora do you still have the email so we can copy it here?

**Comment by jeet-vora** [comment]
The issue has been resolved 

Raja,
We have received your message and will make every effort to respond to you within a reasonable amount of time.

First Name: Raja
Last Name: Mazumder
Email: [mazumder@gwu.edu](mailto:mazumder@gwu.edu)
Subject: technical
Message: https://glygen.org/publication/PubMed/30814731 not working. Clicked from https://glygen.org/protein/P38484 SNV section position 168. Using Chrome.


https://beta.glygen.org/publication/PubMed/30814731

![Image](https://user-images.githubusercontent.com/25825266/229187176-2af367cc-2e54-4e36-999e-6070c2818309.png)

Please close if you are satisfied
