### ISSUE TITLE
Dead link for other residue in glycan composition

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#124]
**Problem**
Glycan and motif details pages that have glycans with "Other" residues have a link for "Other" that ends up on a 404 page in PubChem. We need to remove these links.

**Solution**
In the API this is send as follows:
```
    "composition": [ 
        { 
          "residue": "hexa",  
          "count": 1,  
          "url": "https://pubchem.ncbi.nlm.nih.gov/compound/610",  
          "name": "Hexuronic Acid",  
          "cid": "610" 
        },  
        { 
          "residue": "other",  
          "count": 3,  
          "url": "https://pubchem.ncbi.nlm.nih.gov/compound/0",  
          "name": "Other",  
          "cid": "0" 
```
Remove the "url" and "cid" property of the "other" residue. Once this is implemented assigned the ticket to @sujeetvkulkarni to check if that breaks glycan and motif details pages.

**Comment by kmartinez834** [comment]
@rykahsay Can you remove "url" and "cid" from API for monosaccharides with cid "0" in the file **generated/misc/monosaccharide_residue_name.csv**

API result should look like this:
```
         { 
          "residue": "other",  
          "count": 3,  
          "name": "Other"
         }
```

**Comment by rykahsay** [comment]
Fixed on tst

<img width="766" alt="image" src="https://user-images.githubusercontent.com/20584876/208289532-54759689-b180-4942-bcba-e5dbdd024111.png">
