### ISSUE TITLE
The logo appears to be reduced in this version. I think it was a bit large and ratio was looking good. If it is not my browser and screen size please take a look. jkv

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#132]
Description

Note:

The logo appears to be reduced in this version. I think it was a bit large and ratio was looking good. If it is not my browser and screen size please take a look.
jkv

https://app.pageproofer.com/to/note/217014
Reported by: myGlyGen@gmail.com

Window Size: 1366 x 626
Screen Size: 1366 x 768
Browser: Firefox version: 83.0
Platform: Windows version: 10.0

**Comment by ReneRanzinger** [comment]
@jeet-vora Is this still an open issue?

**Comment by jeet-vora** [comment]
No
