### ISSUE TITLE
Test large phosphorylation data 

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#133]
Description

PMID: 20068231

**Comment by ReneRanzinger** [comment]
@jeet-vora can you please find out which protein this paper was attached to? I think it was removed because it had a huge amount of phosphorylation sites.

**Comment by jeet-vora** [comment]
P55081-1
P42166-1
O43768-1
Q15651-1

**Comment by jeet-vora** [comment]
Solution
1) Server side pagination (talk to Robel)


Other example (Glycan - G49108TO) with 9000+ proteins

**Comment by jeet-vora** [comment]
@rykahsay 

https://tst.glygen.org/publication/PubMed/20068231
The PMID detail page produces error. The PMID contains large number of proteins which might be causing error.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/25825266/216151039-c7ef88b5-3811-46c6-9b30-b0df1adf5ea9.png">

**Comment by rykahsay** [comment]
I have transferred this to the glygen-issues repo
