### ISSUE TITLE
Direct links to CFDE

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#140]
For one of the Tuesday meetings.

From Raja:

Can we link from our protein pages to 

[Gene and Drug Landing Page Aggregator](https://cfde-gene-pages.cloud/gene/EGFR) 

This will

help us collaborate with other DCCs

allow users to explore DCC data which is outside of common resources at EBI and NCBI.

**Comment by ReneRanzinger** [comment]
Jeet will look into this in 2.2
