### ISSUE TITLE
data source information can also be added here. jkv

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#142]
Description

Note:

data source information can also be added here. jkv

https://app.pageproofer.com/to/note/263060
Reported by: myGlyGen@gmail.com

Window Size: 1920 x 924
Screen Size: 1920 x 1080
Browser: Firefox version: 97.0
Platform: Windows version: 10.0

Sujeet Kulkarni 
April 15, 2022 at 12:17 PM

https://tst.glygen.org/publication/PubMed/1482348

Edit

Delete

Sujeet Kulkarni 
April 1, 2022 at 3:46 PM
 "glycan_expression": [] section in publication detail api does not contain evidence information for both cell_line and tissue.https://api.tst.glygen.org/publication/detail?query={%22id%22:%221482348%22,%22type%22:%22PubMed%22}

I have sent an email to Robel.

**Comment by jeet-vora** [comment]
Adding data sources to publication detail pages. This is now resolved
