### ISSUE TITLE
Organism filters: Search for all glycans gives (0) results for HCV-Japanese and HCoV-SARS. Can these

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#143]
Description

Note:

Organism filters: Search for all glycans gives (0) results for HCV-Japanese and HCoV-SARS. Can these options be removed if not applicable? Also, Rat and Rattus appear as two separate filters, rather than one &quot;Rat&quot; filter.

https://app.pageproofer.com/to/note/263520
Reported by: myGlyGen@gmail.com

Window Size: 2560 x 1292
Screen Size: 1920 x 1080
Device: WebKit
Browser: Chrome version: 100.0.4896.60
Platform: Windows version: 10.0

Sujeet Kulkarni 
May 10, 2022 at 12:33 PM
Edited
[https://api.glygen.org/glycan/search?query={"operation":"AND","query_type":"search_glycan","glycan_name":""}](https://api.glygen.org/glycan/search?query=%7B%22operation%22:%22AND%22,%22query_type%22:%22search_glycan%22,%22glycan_name%22:%22%22%7D)

[https://api.glygen.org/glycan/list?query={"id":"61d938ced41bb4484424e755bd2b5a32","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}](https://api.glygen.org/glycan/list?query=%7B%22id%22:%2261d938ced41bb4484424e755bd2b5a32%22,%22offset%22:1,%22sort%22:%22hit_score%22,%22limit%22:20,%22order%22:%22desc%22,%22filters%22:%5B%5D%7D)

Edit

Delete

rene@ccrc.uga.edu 
April 1, 2022 at 4:27 PM

Both, questions for Jeet/Robel on Tuesday.

**Comment by ReneRanzinger** [comment]
This is resolved.
