### ISSUE TITLE
Organism filters (on Advanced Search results page - see attached) includes additional organisms - can

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#144]
Description

Note:

Organism filters (on Advanced Search results page - see attached) includes additional organisms - can drop down menu be expanded to include all possible organisms?

https://app.pageproofer.com/to/note/263522
Reported by: myGlyGen@gmail.com

Window Size: 2560 x 1292
Screen Size: 1920 x 1080
Device: WebKit
Browser: Chrome version: 100.0.4896.60
Platform: Windows version: 10.0

![image](https://user-images.githubusercontent.com/13891482/206550394-885245c5-532c-4550-a947-f647973c8215.png)

rene@ccrc.uga.edu 
April 1, 2022 at 4:30 PM
Also Tuesday. Here its essentially done what she requested in Organism filters: Search for all glycans gives (0) results for HCV-Japanese and HCoV-SARS. Can these

**Comment by ReneRanzinger** [comment]
This is resolved.
