### ISSUE TITLE
By PTM should have top categories for the sub categories shown here for the glycosylation. The top most

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#147]
Description

Note:

By PTM should have top categories for the sub categories shown here for the glycosylation.  The top most category can be glycosylation followed by N-Glycosylation, O-Glycosylation and then the reported and predicted categories as shown now nested under them. jkv

https://app.pageproofer.com/to/note/267237
Reported by: myGlyGen@gmail.com

Window Size: 1366 x 615
Screen Size: 1366 x 768
Browser: Firefox version: 94.0
Platform: Windows version: 10.0

rene@ccrc.uga.edu 
May 5, 2022 at 4:27 PM

We need to talk with Jeet about this. One the one side Robel does not support these top level options and I do not want to “simulate” them using OR. On the other side I think 3 level will be to confusing.

**Comment by ReneRanzinger** [comment]
@jeet-vora Do you remember what this was about. Is this still an open request?

**Comment by jeet-vora** [comment]
no do not remember this request
