### ISSUE TITLE
Two glycans (&quot;G53621MK&quot;, &quot;G82740LG&quot;) have &quot;-1&quot; in No of Sugars field.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#148]
Description

Note:

Two glycans (&quot;G53621MK&quot;, &quot;G82740LG&quot:wink: have &quot;-1&quot; in No of Sugars field.  These are the only glycans with Byonic: &quot;%&quot; (Karina)

https://app.pageproofer.com/to/note/271822
Reported by: myGlyGen@gmail.com

Window Size: 2880 x 1453
Screen Size: 1920 x 1080
Device: WebKit
Browser: Chrome version: 102.0.5005.115
Platform: Windows version: 10.0

![image](https://user-images.githubusercontent.com/13891482/206552703-d36454cf-671d-4bc8-b333-d6e5f032797a.png)

**Comment by ReneRanzinger** [comment]
This is resolved.
