### ISSUE TITLE
License page 

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#149]
Hi Rene,

Can you please change to CC-BY-4.0 for GlyConnect?
[GlyConnect Help](https://glyconnect.expasy.org/help)

Thanks,
Raja

**Comment by ReneRanzinger** [comment]
This is on the [license page](https://www.glygen.org/license/).

**Comment by sujeetvkulkarni** [comment]
cb9dccf379ea3f400479e5fbc473464cbe409d97
