### ISSUE TITLE
Add section &quot;in Xref's&quot; in global search search. for e.g If I add a Pubchem CID 6857384 in global search, it gives me zero results even though we have it as a xref for GlyTouCan G64007OP -Rahi

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#150]
Description

Note:

Add section &quot;in Xref's&quot; in global search search.
for e.g If I add a Pubchem CID 6857384 in global search, it gives me zero results even though we have it as a xref for GlyTouCan G64007OP
-Rahi

https://app.pageproofer.com/to/note/167047
Reported by: myGlyGen@gmail.com

Window Size: 1745 x 807
Screen Size: 1920 x 1080
Device: WebKit
Browser: Chrome version: 79.0.3945.79
Platform: Windows version: 10.0

rene@ccrc.uga.edu 
July 21, 2020 at 9:51 PM

Need to talk with Robel

**Comment by ReneRanzinger** [comment]
We have removed that feature entirely.
