### ISSUE TITLE
Publish the datasets from beta to prd for CFDE release

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#153]
**Process these files and push to production**

- Glycan_pubchem_status.csv (goes to CFDE) …
- hcv1a_protein_masterlist.csv
- hcv1b_protein_masterlist.csv
- sarscov1_protein_masterlist.csv
- sarscov2_protein_masterlist.csv

**Push to production**
human_protein_masterlist.csv
glycan_masterlist.csv
human_proteoform_glycosylation_sites_glyconnect.csv
human_proteoform_glycosylation_sites_uniprotkb.csv
human_proteoform_glycosylation_sites_unicarbkb.csv
human_proteoform_glycosylation_sites_gptwiki.csv
human_proteoform_glycosylation_sites_o_glcnac_mcw.csv
mouse_protein_masterlist.csv
mouse_proteoform_glycosylation_sites_glyconnect.csv
mouse_proteoform_glycosylation_sites_uniprotkb.csv
mouse_proteoform_glycosylation_sites_unicarbkb.csv
mouse_proteoform_glycosylation_sites_o_glcnac_mcw.csv
rat_protein_masterlist.csv
rat_proteoform_glycosylation_sites_glyconnect.csv
rat_proteoform_glycosylation_sites_uniprotkb.csv
rat_proteoform_glycosylation_sites_unicarbkb.csv
rat_proteoform_glycosylation_sites_o_glcnac_mcw.csv
hcv1a_proteoform_glycosylation_sites_literature.csv
hcv1a_proteoform_glycosylation_sites_uniprotkb.csv
hcv1b_proteoform_glycosylation_sites_uniprotkb.csv
sarscov1_proteoform_glycosylation_sites_literature.csv
sarscov1_proteoform_glycosylation_sites_unicarbkb.csv
sarscov2_proteoform_glycosylation_sites_uniprotkb.csv
sarscov2_proteoform_glycosylation_sites_uniprotkb.csv
sarscov2_proteoform_glycosylation_sites_glyconnect.csv
fruitfly_protein_masterlist.csv
fruitfly_proteoform_glycosylation_sites_glyconnect.csv
fruitfly_proteoform_glycosylation_sites_o_glcnac_mcw.csv
Fruitfly_proteoform_glycosylation_sites_uniprotkb.csv

**Comment by rykahsay** [comment]
@jeet-vora  Check beta-data.glygen.org and make sure these datasets are appearing as expected before I push 2.0.2 to production

**Comment by jeet-vora** [comment]
The files look good on beta. Push to prd. @rykahsay 

Have you pushed all the GlyGen datasets to beta along with the above? Yes or No

**Possible bug:** The date in records for 2.0.2 shows Sept 19 rather than a December date.
https://beta-data.glygen.org/GLY_000001

<img width="819" alt="image" src="https://user-images.githubusercontent.com/25825266/208134018-5d1d5c13-a38b-4d78-a7b8-963c84147758.png">

**Comment by rykahsay** [comment]
Yes, 2.0.2 on beta is a fresh push not a patch

**Comment by rykahsay** [comment]
Done! The release date is ok
