### ISSUE TITLE
Process BioMuta Data

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#157]
The biomuta v5 data is present in **data/projects/glygen/downloads/biomuta/v-5.0/compiled/biomuta_v5.csv** (README by Ned - https://biomuta.readthedocs.io/en/latest/ and https://github.com/GW-HIVE/biomuta/blob/master/docs)

biomuta_v5.csv is compiled of 
/data/projects/glygen/downloads/biomuta/v-5.0/compiled/civic_missense_biomuta_v5.csv
/data/projects/glygen/downloads/biomuta/v-5.0/compiled/cosmic_missense_biomuta_v5.csv
/data/projects/glygen/downloads/biomuta/v-5.0/compiled/icgc_missense_biomuta_v5.csv
/data/projects/glygen/downloads/biomuta/v-5.0/compiled/tcga_missense_biomuta_v5.csv

To process the file biomuta_v5.csv extract from the input file

uniprotkb_canonical_ac as uniprotkb_canonical_ac and validate it against latest masterlist
aa_pos as aa_pos and validate it against latest fasta sequence
ref_aa as ref_aa 
alt_aa as alt_aa
chr_id as chr_id
start_pos | end_pos as chr_pos
ref_nt as ref_nt
alt_nt as alt_nt
source as data_source
spilt do_name into do_id and do_name

patients_positive | patients_tested | mut_freq are not present in biomuta_v5.csv. These info come from TCGA. The file that needs to be parsed is glygen/downloads/biomuta/v-5.0/tcga/clinical_information.csv. Target the fields submitter_id for patient and project_id for cancer. The submitter id is present in compiled/biomuta_v5.csv as _sample_name_ to map the info.

There are other fields that are added as post processing steps.

**to human_protein_mutation_cancer.csv** 

xref_key|xref_id|filter_flags|glyco_annotation|mim_id|somatic_status|minor_allelic_frequency|patients_positive|patients_tested|mut_freq      
human_protein_mutation_cancer_glycoeffect as post processing steps.

**to human_protein_mutation_cancer_glycoeffect**
xref_key|xref_id|filter_flags|mim_id|somatic_status|minor_allelic_frequency|is_known_glycoprotein|motif_start|ref_motif|alt_motif|effect

note - GMAF - Global Minor Allelic Freq and dbSNP ids are present in the input TCGA file sdata/projects/glygen/downloads/biomuta/v-5.0/tcga/biomuta_tcga.csv but has not been extracted into compiled/biomuta_v5.csv.

**Field comparison**

**human_protein_mutation_cancer.csv**
uniprotkb_canonical_ac,aa_pos,ref_aa,alt_aa,chr_id,chr_pos,ref_nt,alt_nt,patients_positive,patients_tested,mut_freq,data_source,do_id,do_name,xref_key,xref_id,filter_flags,glyco_annotation,mim_id,somatic_status,minor_allelic_frequency,,,,
**human_protein_mutation_cancer_glycoeffect**
uniprotkb_canonical_ac,aa_pos,ref_aa,alt_aa,chr_id,chr_pos,ref_nt,alt_nt,patients_positive,patients_tested,mut_freq,data_source,do_id,do_name,xref_key,xref_id,filter_flags,mim_id,somatic_status,minor_allelic_frequency,is_known_glycoprotein,motif_start,ref_motif,alt_motif,effect
**biomuta_v5.csv**
uniprotkb_canonical_ac,aa_pos,ref_aa,alt_aa,chr_id,start_pos|end_pos,ref_nt,alt_nt,,,,source,do_name,do_name,,,,,,,,,,,

Additional info
**List of cancers in BioMuta**
    Urinary Bladder Cancer (DOID:11054)
    Breast Cancer (DOID:1612)
    Colorectal (DOID:9256)
    Esophageal Cancer (DOID:5041)
    Head and Neck Cancer (DOID:11934)
    Kidney Cancer (DOID:263)
    Liver Cancer (DOID:3571)
    Lung Cancer (DOID:1324)
    Prostate Cancer (DOID:10283)
    Stomach Cancer (DOID:10534)
    Thyroid Gland Cancer (DOID:1781)
    Uterine Cancer (DOID:363)
    Cervical Cancer (DOID:4362)
    Brain Cancer (DOID:1319)
    Hematologic Cancer (DOID:2531)
    Adrenal Gland Cancer (DOID:3953)
    Pancreatic Cancer (DOID:1793)
    Ovarian Cancer (DOID:2394)
    Skin Cancer (DOID:4159)

TCGA Projects were mapped to DOID parent terms using the following table (generated from previous Biomuta mapping):
https://github.com/GW-HIVE/biomuta/blob/master/docs/source/tcga_convert.rst
+------------+------------------------+--------------+
| DO_slim_id | DO_slim_name           | TCGA_project |
+============+========================+==============+
| DOID:5041  | esophageal cancer      | TCGA-ESCA    |
+------------+------------------------+--------------+
| DOID:2531  | hematologic cancer     | TCGA-DLBC    |
+------------+------------------------+--------------+
| DOID:9256  | colorectal cancer      | TCGA-READ    |
+------------+------------------------+--------------+
| DOID:1319  | brain cancer           | TCGA-GBM     |
+------------+------------------------+--------------+
| DOID:1319  | brain cancer           | TCGA-LGG     |
+------------+------------------------+--------------+
| DOID:1781  | thyroid cancer         | TCGA-THCA    |
+------------+------------------------+--------------+
| DOID:11054 | urinary bladder cancer | TCGA-BLCA    |
+------------+------------------------+--------------+
| DOID:363   | uterine cancer         | TCGA-UCEC    |
+------------+------------------------+--------------+
| DOID:169   | neuroendocrine tumor   | TCGA-PCPG    |
+------------+------------------------+--------------+
| DOID:4362  | cervical cancer        | TCGA-CESC    |
+------------+------------------------+--------------+
| DOID:363   | uterine cancer         | TCGA-UCS     |
+------------+------------------------+--------------+
| DOID:3277  | thymus cancer          | TCGA-THYM    |
+------------+------------------------+--------------+
| DOID:3571  | liver cancer           | TCGA-LIHC    |
+------------+------------------------+--------------+
| DOID:11934 | head and neck cancer   | TCGA-HNSC    |
+------------+------------------------+--------------+
| DOID:2174  | ocular cancer          | TCGA-UVM     |
+------------+------------------------+--------------+
| DOID:4159  | skin cancer            | TCGA-SKCM    |
+------------+------------------------+--------------+
| DOID:9256  | colorectal cancer      | TCGA-COAD    |
+------------+------------------------+--------------+
| DOID:3953  | adrenal gland cancer   | TCGA-ACC     |
+------------+------------------------+--------------+
| DOID:1793  | pancreatic cancer      | TCGA-PAAD    |
+------------+------------------------+--------------+
| DOID:2994  | germ cell cancer       | TCGA-TGCT    |
+------------+------------------------+--------------+
| DOID:1324  | lung cancer            | TCGA-LUSC    |
+------------+------------------------+--------------+
| DOID:1790  | malignant mesothelioma | TCGA-MESO    |
+------------+------------------------+--------------+
| DOID:2394  | ovarian cancer         | TCGA-OV      |
+------------+------------------------+--------------+
| DOID:1115  | sarcoma                | TCGA-SARC    |
+------------+------------------------+--------------+
| DOID:263   | kidney cancer          | TCGA-KIRP    |
+------------+------------------------+--------------+
| DOID:10534 | stomach cancer         | TCGA-STAD    |
+------------+------------------------+--------------+
| DOID:2531  | hematologic cancer     | TCGA-LAML    |
+------------+------------------------+--------------+
| DOID:10283 | prostate cancer        | TCGA-PRAD    |
+------------+------------------------+--------------+
| DOID:1324  | lung cancer            | TCGA-LUAD    |
+------------+------------------------+--------------+
| DOID:1612  | breast cancer          | TCGA-BRCA    |
+------------+------------------------+--------------+
| DOID:263   | kidney cancer          | TCGA-KIRC    |
+------------+------------------------+--------------+
| DOID:263   | kidney cancer          | TCGA-KICH    |
+------------+------------------------+--------------+

**Comment by rykahsay** [comment]
Why do I see rows like this --> aa change without nt change?

sample_name,chr_id,start_pos,end_pos,ref_nt,alt_nt,aa_pos,ref_aa,alt_aa,do_name,uniprotkb_canonical_ac,source
TCGA-OR-A5KB,12,20733097,20733097,T,T,459,Y,N,DOID:3953 / adrenal gland cancer,Q9NYB5-1,tcga
TCGA-OR-A5KU,2,233445642,233445642,C,C,405,P,L,DOID:3953 / adrenal gland cancer,Q16760-1,tcga

**Comment by rykahsay** [comment]
Dataset has been created, please check

**Comment by jeet-vora** [comment]
Observation
1. There are 43 cancers in the current dataset whereas the previous dataset has only 19 cancers as Raja requested (cancers in the info above)
2. There are 50K+ rows in the new dataset whereas the previous dataset 17K dataset (2.5x more entries in new ds)
3. The new dataset contains entries of isoforms as well
4. There are entries from cosmic that contain no cancer info - we need to filter them off.

Question - 
1. How are you filtering entries from the source to the dataset?
2.

**Comment by rykahsay** [comment]
It looks like the following comparison rows with version 1.12.3 have issues

['rowcount', 192967, 524983]
['data_source', 2, 4]
['do_id', 21, 42]
['do_name', 21, 44]
['filter_flags', 21135, 39367]
['glyco_annotation', 126, 160]
['mim_id', 1, 1]
['minor_allelic_frequency', 1, 1]
['mut_freq', 100, 96]
['patients_positive', 61, 48]
['patients_tested', 128, 32]
['uniprotkb_canonical_ac', 17085, 15761]
['xref_id', 17085, 15761]
['xref_key', 1, 1]

**Comment by rykahsay** [comment]
cutoff_one = 1.0
cutoff_two = 10       
combo_id = "%s %s %s %s" % (canon, aa_pos, ref_aa, alt_aa)
       

**A mutation (combo_id) is considered if it satisfies one or more from these conditions**

-         if mut_freq >= cutoff_one: ===> flag_label = "patient freq. (%s%s)" % (mut_freq, "%")
-         if patients_positive >= cutoff_two: ===> flag_label = "patient count (%s/%s)"%(patients_positive,patients_tested)
-         if cancer_count >= 3: ===> flag_label = "num. of cancers (%s)" % (cancer_count)
-         if combo_id in clinvar_ann and do_id in clinvar_ann[combo_id]: ===> flag_label = "DB annot. (%s)" % (1)
-         if combo_id in lit_ann and do_id in lit_ann[combo_id]: ===> flag_label = "Lit. mined (%s)" % (len(lit_list[combo_id]))
-         if "there is glycosylation effect": ===> flag_label = "%s (%s->%s)" % (eff,ref_m,alt_m)
