### ISSUE TITLE
Create protein accessions dataset for Nathan from EBI

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#159]
More information to be added

**Comment by rykahsay** [comment]
@jeet-vora @kmartinez834 
You will create this yourself following these commands (please document this)

- cd /software/glygen/
- python dump_protein_masterlist.py

which will create /data/shared/glygen/downloads/glygen_protein_masterlist.csv

**Comment by kmartinez834** [comment]
@edwardsnj the protein masterlist for all species can be found here:  https://data.glygen.org/ln2downloads/glygen_protein_masterlist.csv

Also added to the file tracker: (https://docs.google.com/spreadsheets/d/1PYsMSfi5Z_6ZxHDMM8z5iSEXDOr6SAlzfpx01rWr0zc/edit?usp=sharing)
