### ISSUE TITLE
Drosophila xrefs into the GlyGen mapper tool

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#160]
More information to be added

**Comment by rykahsay** [comment]
I need details ...

**Comment by rykahsay** [comment]
@jeet-vora -- I don't understand the need for this ticket/issue. Is the idmapping API failing for Drosophila IDs? 
When I tried it, it is working  .. 

<img width="577" alt="image" src="https://user-images.githubusercontent.com/20584876/213023888-400d33c1-e851-4902-8225-bf3dc92f00c6.png">

**Comment by jeet-vora** [comment]
worked
