### ISSUE TITLE
Too big error in glycan substructure search

### ISSUE THREAD

**Issue by senaarpinar** [glygener/glygen-frontend#165]
If I use the following GlyoCT for structure search, it is giving "motif too big" error (which is correct):

```
RES
1b:x-dglc-HEX-1:5
2b:b-dglc-HEX-1:5
3b:b-dglc-HEX-1:5
4b:b-dglc-HEX-1:5
5b:b-dglc-HEX-1:5
6b:b-dglc-HEX-1:5
7b:b-dglc-HEX-1:5
8b:b-dglc-HEX-1:5
9b:b-dglc-HEX-1:5
10b:b-dglc-HEX-1:5
11b:b-dglc-HEX-1:5
12b:b-dglc-HEX-1:5
LIN
1:1o(3+1)2d
2:2o(3+1)3d
3:3o(3+1)4d
4:4o(3+1)5d
5:5o(3+1)6d
6:6o(3+1)7d
7:7o(3+1)8d
8:8o(3+1)9d
9:9o(3+1)10d
10:10o(3+1)11d
11:11o(3+1)12d
```
Then replacing it with the following structure, it still gives "motif too big" error but this is incorrect.

```
RES
1b:x-dgal-HEX-1:5
2s:n-acetyl
3b:b-dgal-HEX-1:5
4b:b-dglc-HEX-1:5|6:a
5s:amino
LIN
1:1d(2+1)2n
2:1o(3+1)3d
3:3o(3+1)4d
4:4d(2+1)5n
```

but if we refresh and enter the above structure, this time it gives "invaid input" error.

**Comment by sujeetvkulkarni** [comment]
result count should be 0 or null  if list id will be empty.
assign this to Robel once state issue of motif is too big is addressed.

**Comment by sujeetvkulkarni** [comment]
Api issue blocking it.

**Comment by sujeetvkulkarni** [comment]
efc637d4b969216f74dcf714824b80216efde487

**Comment by sujeetvkulkarni** [comment]
Create a ticket for Robel for result count issue.
Remove "Please Enter valid input" text from generic error case and swap the text with custom error text in custom cases.

**Comment by sujeetvkulkarni** [comment]
result count issue:
https://github.com/glygener/glygen-issues/issues/127

**Comment by sujeetvkulkarni** [comment]
motif is too big error text issue:
https://github.com/glygener/glygen-issues/issues/128

**Comment by sujeetvkulkarni** [comment]
0e440d281b2b995a0a7671af0d119917f94a3f54
