### ISSUE TITLE
Retrieve GlyTouCan ID sets to populate tools information on Glycan Details

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#167]
The tool support property in glycan details JSON is used to decide which outlinking buttons to show on the details page:
```
    "tool_support": {
        "sandbox": "yes", 
        "gnome": "yes"
    }
```

This list needs to be extended to include the gnome restrictions that Nathan implemented (see #32). To retrieve the list of Sandbox glycans and the gnome lists Robel retrieve them live when generating the datasets (no need for @kmartinez834 to download them manually). Based on these lists for some glycans the "tool_support" list will have additional properties. Based on #32 frontend will decide which ones to show. After this is implemented assign the ticket to @ReneRanzinger .

**Comment by ReneRanzinger** [comment]
@edwardsnj provided:
* Sandbox ALL: https://glygen.ccrc.uga.edu/sandbox/api/list.php?par=&mode=all (JSON based list) 
* GNOME Restriction: https://raw.githubusercontent.com/glygen-glycan-data/GNOme/master/restrictions/<Restrictions>.valid-accessions.txt

Where <Restrictions> in {GlyGen, GlyGen_NGlycans, GlyGen_OGlycans, Sandbox_NGlycans, Sandbox_OGlycans}. Note that we don’t currently need the GlyGen restriction valid accession set because anything in GlyGen should be supported.

**Comment by kmartinez834** [comment]
@ReneRanzinger and @edwardsnj can you verify the GNOME restriction file names referenced above?  

I'm currently seeing the following files in restrictions/*.valid-accessions.txt

[BCSDB.valid-accessions.txt](https://github.com/glygen-glycan-data/GNOme/blob/master/restrictions/BCSDB.valid-accessions.txt)
[GlyCosmos.valid-accessions.txt](https://github.com/glygen-glycan-data/GNOme/blob/master/restrictions/GlyCosmos.valid-accessions.txt)
[GlyGen.valid-accessions.txt](https://github.com/glygen-glycan-data/GNOme/blob/master/restrictions/GlyGen.valid-accessions.txt)
[GlyGenBeta.valid-accessions.txt](https://github.com/glygen-glycan-data/GNOme/blob/master/restrictions/GlyGenBeta.valid-accessions.txt)
[GlycoTree_NGlycans.valid-accessions.txt](https://github.com/glygen-glycan-data/GNOme/blob/master/restrictions/GlycoTree_NGlycans.valid-accessions.txt)
[GlycoTree_OGlycans.valid-accessions.txt](https://github.com/glygen-glycan-data/GNOme/blob/master/restrictions/GlycoTree_OGlycans.valid-accessions.txt)

**Comment by kmartinez834** [comment]
@rykahsay we need to extend the tool support property in glycan details JSON. Are you pulling this information from datasets or on the fly?

@ReneRanzinger can you confirm that this is what you're looking for:
```
    "tool_support": {
        "sandbox": "", 
        "gnome": "",
        "gnome_glygen": "",
        "gnome_glygen_nglycans": "",
        "gnome_glygen_oglycans": "",
        "gnome_glycotree_nglycans": "",
        "gnome_glycotree_oglycans": "",
    }
```

**Comment by ReneRanzinger** [comment]
@kmartinez834 yes backend should support all options. If #32 says we don't want to expose all of them to the user frontend will take care of this.

**Comment by kmartinez834** [comment]
Steps for @rykahsay :
1. Add the following tools to unreviewed/glycan_toolsupport.csv.  Accession lists are located at downloads/gnome/current/

|tool | source file| 
--- | --- | 
|gnome_glygen|GlyGen.valid-accessions.txt|
|gnome_glygen_nglycans|GlyGen_NGlycans.valid-accessions.txt|
|gnome_glygen_oglycans|GlyGen_OGlycans.valid-accessions.txt|
|gnome_glycotree_nglycans|GlycoTree_NGlycans.valid-accessions.txt|
|gnome_glycotree_oglycans|GlycoTree_OGlycans.valid-accessions.txt|


3. https://api.glygen.org//glycan/detail// "tool support" array should look like this:
```
    "tool_support": {
        "sandbox": "", 
        "gnome": "",
        "pdb": "",
        "gnome_glygen": "",
        "gnome_glygen_nglycans": "",
        "gnome_glygen_oglycans": "",
        "gnome_glycotree_nglycans": "",
        "gnome_glycotree_oglycans": "",
    }
```
Note: pdb addition is documented in https://github.com/glygener/glygen-issues/issues/5

**Comment by rykahsay** [comment]
@kmartinez834 --> I have updated glycan_toolsupport.csv, please check.

**Comment by kmartinez834** [comment]
@rykahsay glycan_toolsupport.csv looks good
👍 Number of records in source files matches number of corresponding tool "yes" accessions

Please assign the ticket to @ReneRanzinger when glycan details API has been updated

**Comment by rykahsay** [comment]
@ReneRanzinger 

<img width="493" alt="image" src="https://user-images.githubusercontent.com/20584876/220470635-ad7bb831-118d-4ca6-b876-74a531374689.png">

**Comment by ReneRanzinger** [comment]
The frontend will implement this as part of #103 .
