### ISSUE TITLE
Download sandbox accession list

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-frontend#169]
Run the following to generate accession list for sandbox:

`python /software/glygen/sandbox-xref-download.py`

**Comment by kmartinez834** [comment]
Sandbox accession list has been generated and saved to GlyGen server at downloads/sandbox/current

**Comment by rykahsay** [comment]
I think we need to make downloads for two more files (shown below) --> I have copied those files to sandbox/current/ from the last download

- sandbox/current/accessionlist.csv --> used for glycan_xref_sandbox.csv
- sandbox/current/allPaths.json --> used for glycan_pathway_glycotree.csv
- sandbox/current/glycotree_annotated_glycans.tsv --> used for glycan_enzyme.csv
-

**Comment by kmartinez834** [comment]
@edwardsnj We have the following sandbox files for 2.0, is there any new sandbox data to ingest before we process?

- accessionlist.csv, generated from https://glygen.ccrc.uga.edu/sandbox/api/list.php (Dec 2022)
- glycotree_annotated_glycans.tsv, generated from https://glygen.ccrc.uga.edu/sandbox/api/list.php (same file as Feb 2022)
- allPaths.json, glycan enzyme file provided by Will (Dec 2021)

**Comment by edwardsnj** [comment]
There is an allPaths.json.zip file here: https://github.com/glygen-glycan-data/glycoTree/tree/master/portal/api/paths 

as well as a allPaths2.json file in the same folder. It appears that the two json files (one inside the zip file) are not the same number of bytes.

**Comment by kmartinez834** [comment]
The source files we are ingesting from Sandbox are located here:
https://data.glygen.org/ln2downloads/sandbox/current/
