### ISSUE TITLE
Glyomics web services as tools in GlyGen

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#170]
Should we add @edwardsnj web services as tools in GlyGen?

There are several options:
* Migrate them to the GlyGen server (see substructure search)
* Make a GlyGen GUI but call Nathans webservices
* Just link to Nathans page from the GlyGen menu

**Comment by edwardsnj** [comment]
The page at glyomics.org shows all the web-services currently available to the public. Not all of these have an option for GlyGen restricted accession set logic, but this could be added quite quickly.

**Comment by ReneRanzinger** [comment]
we will focus on Glymage and Gnome for now (2.4). In year 3 we reevaluate next steps for more integrations.
