### ISSUE TITLE
Downloads link produced error on data.glygen.org on both prd and beta

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#174]
example

https://data.glygen.org/ln2data/releases/data/v-x.x.x/reviewed/human_protein_masterlist.csv

<img width="466" alt="image" src="https://user-images.githubusercontent.com/25825266/210590262-0e5d74ce-8184-4f85-9c48-b93a00360abd.png">

<img width="711" alt="image" src="https://user-images.githubusercontent.com/25825266/210590016-57d6162b-13da-4881-bcf0-918781887a34.png">

**Comment by rykahsay** [comment]
@jeet-vora  tried to fix it, please check

**Comment by jeet-vora** [comment]
@rykahsay Issue resolved.

**Comment by jeet-vora** [comment]
Same error occurred again

for https://data.glygen.org/ln2data/releases/data/current/reviewed/protein_glygen_pubchem_xref_mapping.csv

**Comment by rykahsay** [comment]
Maybe you need to clear your cache, this is what I see on my side:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/20584876/211791742-df84dc71-5c95-46f7-bc1b-915bd23d01a8.png">


<img width="805" alt="image" src="https://user-images.githubusercontent.com/20584876/211791505-bb09dc8f-b3d4-4e58-af9e-d3373293d3de.png">

**Comment by rykahsay** [comment]
@jeet-vora  check now

**Comment by jeet-vora** [comment]
resolved
