### ISSUE TITLE
Sequence search for full string of glycan sequence does not work in global search

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#177]
https://www.glygen.org/glycan/G17689DH#Digital-Sequence

alpha-D-Neup5Ac-(2->3)-beta-D-Galp-(1->4)-beta-D-GlcpNAc-(1->2)-alpha-D-Manp-(1->3)[alpha-D-Neup5Ac-(2->3)-beta-D-Galp-(1->4)-beta-D-GlcpNAc-(1->2)-alpha-D-Manp-(1->6)]-beta-D-Manp-(1->4)-beta-D-GlcpNAc-(1->4)[alpha-L-Fucp-(1->6)]-beta-D-GlcpNAc-(1->

https://www.glygen.org/global-search-result/alpha-D-Neup5Ac-(2-%3E3)-beta-D-Galp-(1-%3E4)-beta-D-GlcpNAc-(1-%3E2)-alpha-D-Manp-(1-%3E3)%5Balpha-D-Neup5Ac-

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/25825266/210810369-1ccb1ca0-5f9c-46f5-be00-d628dd6ecde3.png">

**Comment by sujeetvkulkarni** [comment]
Need changes from backend.

**Comment by rykahsay** [comment]
fixed --> try it now it will give you sequences

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/20584876/219173247-aa4a53d6-49b9-4470-8e99-3364161dea72.png">

**Comment by sujeetvkulkarni** [comment]
efc637d4b969216f74dcf714824b80216efde487
