### ISSUE TITLE
Data.glygen.org search filter issue

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#178]
The data.glygen.org search filter has an issue. Not all filter options are seen, and nor the datasets are counted correctly.
Why does it say - 530 results found and "100 retrieved" 

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/25825266/210929926-5f81c810-3d93-482b-acfc-1649ae1c59e1.png">

Also it would be nice if the searching is optimized. for eg If I search "rat masterlist" it does not show results. I have to type in "rat proteome masterlist"

<img width="894" alt="image" src="https://user-images.githubusercontent.com/25825266/211071238-f0c30190-e3d8-45f9-ae56-a29f622c2ec0.png">

watcher @kmartinez834

**Comment by rykahsay** [comment]
@jeet-vora  check now

**Comment by jeet-vora** [comment]
Checked
