### ISSUE TITLE
super search issue

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#180]
When the glycan number search is clicked it produces error

<img width="741" alt="image" src="https://user-images.githubusercontent.com/25825266/211458469-de71027a-35ee-4257-9fb5-bb0a6976f3d5.png">

https://www.glygen.org/glycan-list/fefcac7aa97485209316d419e1ee8e7f/sups
<img width="776" alt="image" src="https://user-images.githubusercontent.com/25825266/211458310-294402cc-e528-482d-b941-be856be75202.png">

**Comment by rykahsay** [comment]
fixed --> please check

**Comment by jeet-vora** [comment]
Issue resolved
