### ISSUE TITLE
Expose all APIs to Swagger for API testing

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#181]
Watcher @sujeetvkulkarni @ReneRanzinger

**Comment by rykahsay** [comment]
--> please have @JingyueWu have test it

**Comment by kmartinez834** [comment]
@rykahsay https://api.tst.glygen.org/ is currently down

I'm getting a 503 Service Unavailable

**Comment by kmartinez834** [comment]
@JingyueWu Your task: test all api's on https://api.tst.glygen.org/

1. Click on POST dropdown
![image](https://user-images.githubusercontent.com/90285371/215627879-38a8bcc4-0ced-4733-86ab-5001106c54f4.png)

2. Click Try it out button
![image](https://user-images.githubusercontent.com/90285371/215628524-1c56cdc0-dc31-4b0a-bce8-090350a1ac3a.png)

3. Click Execute
![image](https://user-images.githubusercontent.com/90285371/215628580-5c9a71b3-9fdc-4f0b-88f2-a9d87ae02c7d.png)

4. Make sure you get successful response
![image](https://user-images.githubusercontent.com/90285371/215628720-f23a71bf-b3b1-490e-8181-f271d278f5bf.png)

**Comment by JingyueWu** [comment]
@jeet-vora This task is completed by my end. Please see below and review:

1. Most of API are working fine
2. There are cases where after execution, I see "Error: INTERNAL SERVER ERROR" and "Success" at the same time, which brings the question: what does it indicate? Which message should I go with? (captured in screenshots below)
e.g. /data/download/
![Screen Shot 2023-02-06 at 3 31 17 PM](https://user-images.githubusercontent.com/61590108/217078609-5b5b198b-545f-4a9b-a784-c06bcbb24c3b.png)

e.g. /typeahead/categorized_typeahead
![Screen Shot 2023-02-06 at 3 33 05 PM](https://user-images.githubusercontent.com/61590108/217078945-9bac87f0-c656-4877-8453-74bcdc2306d6.png)

e.g. /typeahead/global_typeahead/
![Screen Shot 2023-02-06 at 3 33 41 PM](https://user-images.githubusercontent.com/61590108/217079058-c58d7973-a9fb-45fb-9093-c6fabae868ee.png)

e.g. /typeahead/typeahead/
![Screen Shot 2023-02-06 at 3 34 43 PM](https://user-images.githubusercontent.com/61590108/217079239-58393203-15fe-4a9a-8163-d2bd11a18544.png)

e.g. /auth/contact/
![Screen Shot 2023-02-06 at 3 35 47 PM](https://user-images.githubusercontent.com/61590108/217079402-d5d520ed-da84-47bf-a65f-db1a3f3e2146.png)

e.g. /auth/login/
![Screen Shot 2023-02-06 at 3 36 36 PM](https://user-images.githubusercontent.com/61590108/217079582-28c5beec-f2ae-409f-a071-487036931643.png)

e.g. /auth/register/
![Screen Shot 2023-02-06 at 3 37 21 PM](https://user-images.githubusercontent.com/61590108/217079744-81880083-08d0-4db0-a211-a95258f583b9.png)

e.g. /video/detail/
![Screen Shot 2023-02-06 at 3 52 39 PM](https://user-images.githubusercontent.com/61590108/217083056-13423935-d529-4717-82ec-ed302aa0fb4a.png)

e.g. /job/delete/
![Screen Shot 2023-02-06 at 3 54 55 PM](https://user-images.githubusercontent.com/61590108/217083428-a9b9d84b-d1f5-42a8-be88-81a4808b66fc.png)

**Comment by rykahsay** [comment]
@JingyueWu --> please create a new ticket (in the glygener/glygen-issues repo) with screenshots of the failed APIs only. When you take a screenshot, please include the request input you are sending

**Comment by rykahsay** [comment]
I am closing this ticket and starting a new issue
