### ISSUE TITLE
Setup URL for array repository

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#182]
Please have Dacian create a GlyGen subdomain for the array repository: 
https://array.glygen.org

It should point to this URL:
https://glygen.ccrc.uga.edu/ggarray/

**Comment by ReneRanzinger** [comment]
Dacian create the subdomain but it redirects to the URL rather than working as proxy. Once you hit return the URL changes to https://glygen.ccrc.uga.edu/ggarray/. That is not what we wanted with regards to branding. He should use mod_proxy or mod_rewrite.

**Comment by ReneRanzinger** [comment]
@rykahsay It was working a few days about but now it returns a 500 error:
```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at stremtan@email.gwu.edu to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

The target URL is working fine.

**Comment by rykahsay** [comment]
He has fixed it now, please check

**Comment by ReneRanzinger** [comment]
Still not working properly. If you type [https://array.glygen.org](https://array.glygen.org) in your browser you end up with 
[https://array.glygen.org/ggarray/](https://array.glygen.org/ggarray/). There should be no URL change.

**Comment by rykahsay** [comment]
Check now

**Comment by ReneRanzinger** [comment]
Still not working. Connection times out (at least outside GW network). Please test before changing the ticket (New private browser window to avoid cache issues).

**Comment by rykahsay** [comment]
@ReneRanzinger -- please read message below from Dacian. Can we leave it alone the way it? What is the harm?


=======================
I cannot do that. 

If he wants that, he will have to change his uga domain to be a subdomain and not a folder

e.g.
https://glygen.ccrc.uga.edu/ggarray/ -> https://ggarray.glygen.ccrc.uga.edu/

or something similar

If he has the code that can do what he is looking for I am happy to implement it on the apache, but I was unable to do that.
This is the current working section:

<VirtualHost *:443>
    ServerName [array.glygen.org](http://array.glygen.org/)
    Header set Access-Control-Allow-Origin "*"
    SSLEngine on
    SSLProxyEngine on
    SSLProtocol all -SSLv2 -SSLv3
    SSLCipherSuite HIGH:3DES:!aNULL:!MD5:!SEED:!IDEA
    SSLCertificateFile /etc/pki/tls/certs/glygen.org.crt
    SSLCertificateKeyFile /etc/pki/tls/private/glygen.org.key
    SSLCertificateChainFile /etc/pki/ca-trust/source/anchors/InCommonTrustChain.crt
    RewriteEngine on
    RewriteRule "^/$" "/ggarray/" [L,R]
    ProxyPass /ggarray/ https://glygen.ccrc.uga.edu/ggarray/
    ProxyPassReverse /ggarray/ https://glygen.ccrc.uga.edu/ggarray/
</VirtualHost>

**Comment by ReneRanzinger** [comment]
I still have trouble to connect to some of the glygen subdomains. If I test now I will not be sure if the problem is here or on GW site. I will assign the ticket back to me and test it once I am back in US.
