### ISSUE TITLE
tst server apis are not working

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#183]
tst server apis are not working. 
It appears that earlier both GET and POST were supported but now only POST methods are supported. Also, earlier https://api.tst.glygen.org/protein/search_init was supported now it looks like
https://api.tst.glygen.org/protein/search_init/  (forward slash in the end of url) is needed. Can you please fix these issues.

**Comment by sujeetvkulkarni** [comment]
For example,
https://api.tst.glygen.org/protein/detail/P14210-1
will return -  500 Internal Server Error00 Internal Server Error

https://api.tst.glygen.org/protein/detail/P14210-1/
will return - 405 METHOD NOT ALLOWED

https://api.tst.glygen.org/protein/search_init
will return -  500 Internal Server Error

https://api.tst.glygen.org/protein/search_init/0
will return - 405 METHOD NOT ALLOWED

https://api.tst.glygen.org/glycan/detail/G17689DH/
will return -  500 Internal Server Error

https://api.tst.glygen.org/glycan/search_init
will return -  500 Internal Server Error

https://api.tst.glygen.org/glycan/search_init/
will return - 405 METHOD NOT ALLOWED

**Comment by rykahsay** [comment]
@sujeetvkulkarni  ... please check now
