### ISSUE TITLE
Follow up with Robel for server access

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#185]
Jingyue follow up with Robel on the email thread to get access to GlyGen server.

**Comment by JingyueWu** [comment]
@rykahsay Just following up -- Can you please grant me access to GlyGen's server? My NetID is jingyue.wu and email is jingyue.wu@email.gwu.edu

**Comment by JingyueWu** [comment]
Dacian just granted me the access to GlyGen server.
