### ISSUE TITLE
Review the integration checklist

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#187]
Review the data integration checklist to understand the steps in integrating a dataset

/data/projects/glygen/checklist/basic_20_checklist.txt

**Comment by JingyueWu** [comment]
@jeet-vora I was able to 
1) Successfully access the GlyGen server
2) Use command lines to navigate from directory to directory
3) Open the basic_checklist.txt and read the data integration instructions

**Question:** when I am at "checklist" directory, I only see one file which is basic_checklist.txt, not basic_20_checklist.txt. I am wondering, are they the same file? If so, did the name get changed?

**Comment by jeet-vora** [comment]
Great. They are the same file.

Best,

*Jeet Vora*
Senior Research Associate
Scientific Coordinator for GlyGen.org
Project Manager for Glycosciences-NIH CFDE
The George Washington University
Ross Hall, Room 559
2300 Eye Street N.W.
Washington, DC 20052
***@***.***
*Pronouns - He/him/his*
