### ISSUE TITLE
GlyGen Testing on TST

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-frontend#189]
Step 1) Login to SMHS or GW VPN....
Step 2) Then enter **tst.glygen.org**  (tst is for test server)
Step 3) Test all searches for links and pages on Explore and tools under menu bar.
You can play around with different options and filters
Step 4) Report any broken link or pages with URL and screenshots in a google document that can be attached here. You can confirm the error by repeating it on glygen.org

 
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/25825266/213002672-ce6eab32-c6c5-43b9-975d-881317689181.png">

**Comment by JingyueWu** [comment]
@jeet-vora This task is completed and all broken links/error messages are reported in [GlyGen Testing on TST Broken Link Report](https://docs.google.com/document/d/1X-rgJ02JFDxcbUnBGaPqoyMkrCdBixPIsOsdnkWpji4/edit?usp=sharing) that I created, please review.

**Comment by jeet-vora** [comment]
@JingyueWu Yes as the tst server is down many APIs are failing.
Once the APIs are back online you can test once again.

**Comment by kmartinez834** [comment]
@JingyueWu APIs are currently up and running

**Comment by JingyueWu** [comment]
@jeet-vora I have explored all tabs and followed the tutorials to try out the examples. All links are functioning. However, there are still several things to note:
1. Under Explore -> List of Motifs: Glycan image are not loading 

![Screen Shot 2023-02-07 at 9 10 28 AM](https://user-images.githubusercontent.com/61590108/217268001-c08af17a-090f-4ec7-8da2-1b48bcc7484b.png)

2. The tutorials for site search and super search appear as "coming soon..." -- Is the team working on it?
