### ISSUE TITLE
data.glygen.org/ln2downloads/* link dead

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-frontend#190]
https://data.glygen.org/ln2downloads/ results in an error:

![image](https://user-images.githubusercontent.com/90285371/213555047-979325bb-33c0-4709-9ae7-3e96f7060247.png)

**Comment by rykahsay** [comment]
Please try it now (you may need to clear your cache)

 https://data.glygen.org/ln2downloads/

**Comment by kmartinez834** [comment]
Link is working
