### ISSUE TITLE
Why glycan search is failing

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-frontend#193]
@sujeetvkulkarni --> can you please tell me which API is failing/causing this behavior shown in the screenshot?

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/20584876/214397140-32385d54-ed0e-4655-bb22-bea20366566b.png">

**Comment by sujeetvkulkarni** [comment]
I performed below glycan search
https://api.tst.glygen.org/glycan/search?query={"operation":"AND","query_type":"search_glycan","glycan_name":"","glycan_identifier":{"glycan_id":"G17689DH","subsumption":"none"}}

This returns
{"status": 0, "error": "exception-error-Y9TVQ8"}

Which causes list api to be called with wrong id
https://api.tst.glygen.org/glycan/list?query={"id":"undefined","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}
which returns 
{"status": 0, "error": "exception-error-UK50M1"}

causing this behaviour.
So glycan/search and /glycan/list both need to be verified.

**Comment by sujeetvkulkarni** [comment]
@rykahsay :
In production if response is given it returns either a valid or empty listid.
In that case it returned Status Code: 200 OK.
But when api fails it returns below response
{
  "error_list": [
    {
      "error_code": "invalid-query-json"
    }
  ]
} 
with Status Code: 500 INTERNAL SERVER ERROR

**Comment by sujeetvkulkarni** [comment]
exception errors should be in standard error format with status 500 INTERNAL SERVER ERROR.

**Comment by rykahsay** [comment]
@sujeetvkulkarni  --> I know this could mean considerable change on your side but since we are moving towards doing things properly, the way you call the following list of APIs needs to change. 

For the list of APIs given below,  you need to stop sending the JSON as a string as a parameter called "query". In other words, this needs to stop:  
   https://api.tst.glygen.org/glycan/search?query={"glycan_identifier" {"glycan_id":"G17689DH","subsumption":"none"}})


Instead, in React, the request should be made something like this. 

const reqOptions = { 
      method: 'POST', 
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({"glycan_identifier" {"glycan_id":"G17689DH","subsumption":"none"}})
 };
  
fetch("https://api.tst.glygen.org/glycan/search", reqOptions).then((res) => res.json()).then(
      (res) => {console.log(res);},
      (error) => { console.log(error);}
  );
  

LIST OF APIs 
==========
/auth/contact
/auth/register
/auth/login
/auth/tokenstatus
/auth/userinfo
/auth/userupdate
/auth/contactlist
/auth/contactupdate
/auth/contactdelete

/data/download

/event/addnew
/event/update
/event/detail
/event/list
/event/delete

/globalsearch/search

/glycan/search_simple
/glycan/search
/glycan/list

/idmapping/list

/job/results
/job/addnew_old
/job/status
/job/queue
/job/update
/job/detail
/job/list
/job/delete

/log/logging
/log/init
/log/access
/log/grouped

/motif/detail
/motif/list

/protein/search_simple
/protein/search
/protein/list
/protein/alignment

/publication/detail
/publication/list

/seqmapping/search

/supersearch/search
/supersearch/list

/typeahead/typeahead
/typeahead/categorized_typeahead
/typeahead/global_typeahead

/usecases/disease_to_glycosyltransferases
/usecases/genelocus_list
/usecases/ortholog_list
/usecases/glycosequon_list

/video/addnew
/video/list
/video/detail
/video/delete

**Comment by rykahsay** [comment]
@sujeetvkulkarni --> I have tried to correct the error response behavior.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/20584876/214707412-3b3a5d2f-dadd-4b64-9bc1-f809de17b13f.png">

**Comment by sujeetvkulkarni** [comment]
> @sujeetvkulkarni --> I know this could mean considerable change on your side but since we are moving towards doing things properly, the way you call the following list of APIs needs to change.
> 
> For the list of APIs given below, you need to stop sending the JSON as a string as a parameter called "query". In other words, this needs to stop: [https://api.tst.glygen.org/glycan/search?query={"glycan_identifier](https://api.tst.glygen.org/glycan/search?query=%7B%22glycan_identifier)" {"glycan_id":"G17689DH","subsumption":"none"}})
> 
> Instead, in React, the request should be made something like this.
> 
> const reqOptions = { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({"glycan_identifier" {"glycan_id":"G17689DH","subsumption":"none"}}) };
> 
> fetch("https://api.tst.glygen.org/glycan/search", reqOptions).then((res) => res.json()).then( (res) => {console.log(res);}, (error) => { console.log(error);} );
> 
> # LIST OF APIs
> /auth/contact /auth/register /auth/login /auth/tokenstatus /auth/userinfo /auth/userupdate /auth/contactlist /auth/contactupdate /auth/contactdelete
> 
> /data/download
> 
> /event/addnew /event/update /event/detail /event/list /event/delete
> 
> /globalsearch/search
> 
> /glycan/search_simple /glycan/search /glycan/list
> 
> /idmapping/list
> 
> /job/results /job/addnew_old /job/status /job/queue /job/update /job/detail /job/list /job/delete
> 
> /log/logging /log/init /log/access /log/grouped
> 
> /motif/detail /motif/list
> 
> /protein/search_simple /protein/search /protein/list /protein/alignment
> 
> /publication/detail /publication/list
> 
> /seqmapping/search
> 
> /supersearch/search /supersearch/list
> 
> /typeahead/typeahead /typeahead/categorized_typeahead /typeahead/global_typeahead
> 
> /usecases/disease_to_glycosyltransferases /usecases/genelocus_list /usecases/ortholog_list /usecases/glycosequon_list
> 
> /video/addnew /video/list /video/detail /video/delete

@rykahsay 
So you mean we should not use "GET" method and only use "POST" method to call these APIs?

@ReneRanzinger 
This would mean we need make changes API call changes from "GET" to "POST" in all such cases.

**Comment by ReneRanzinger** [comment]
@rykahsay didnt you say that you would support both Get and Post?

@sujeetvkulkarni I thought we only have one JS file that handles all ws requests. Is that correct? How hard would it so modify it or are parts (e.g. URL building) done outside this JS file?

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger We are modifying the parameters here not just the underlying call method. So though we have wrapped axios functionality to make api calls that function would get called from multiple api specific functions and also parameter construction will change for respective functions. So that intermediate api layer would need modifications. It is not hard but it would need testing and api layer related changes.

**Comment by rykahsay** [comment]
@sujeetvkulkarni  --> if it is too much work on your side, I can try to keep accommodating the calls coming from you they are as well as the proper calls coming from the swagger.

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
@ReneRanzinger what you suggest? Should we make this change or continue things as it is, at least for now? In my opinion if the API call does make some updates then it should be POST otherwise if the API is only returning read only data, then it can be both GET and POST. And most of the APIs which Glygen is consuming dont update any objects, so should be both GET and POST.
