### ISSUE TITLE
About us page text change.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#195]
The GlyGen
Global Effort
------------------
GlyGen is a cooperative, global, community-driven project.

An open, standardized environment for independent development and integration of additional research tools by other investigators.

More than 15 investigators in five countries play key roles in the project.

Two years of organized discussion and planning involving nearly 100 investigators.

**Comment by jeet-vora** [comment]
@ReneRanzinger @sujeetvkulkarni 
![image](https://user-images.githubusercontent.com/25825266/215186755-6f91e162-53da-483f-bce9-c8f5911bd683.png)

Remove William York, add him to former members
---------------------------------------------------------

![image](https://user-images.githubusercontent.com/25825266/215186909-33565957-235f-49bf-8c0a-a4c398edfbd9.png)

-Change Advocates to Advisors.
-Remove Michael Pierce, Radoslav Goldman, Nicolle Packer.
-Add Stacy Malaker (place holder for now until we get full details)
----------------------------------------------------------------
Key Collaborators / Co-Investigators
- Tool Development and Data Integration, this subtitle should be below Key Collaborators / Co-Investigators
    -Remove Matthew Campbell, Darren Natale, Karen Ross, Kiyoko Aoki-Kinoshita, Robert Woods.
    - Add Co-Investigator role for Rene and Robel, ask them if they want in the format Co-Investigator, Software - Leade
- Integration with EBI, SIB, NCBI, GlyCosmos, GlyConnect should be the second sub-title
    - Add Kiyoko Aoki-Kinoshita, [Frederique Lisacek and Evan Bolton (already there)] as Consultant. Do not know if we should add Paul Thiessen
- Remove Glycan Array Database Partners subsection. Ask Rene or Mike if they need to be added to Former members
    - Remove Kim Pruitt and Gareth Owen.
- Merge Data Management Team and Web Developers
    - Keep Jeet, Karina, Sujeet and Sena.
    - Remove Tatiana, Sandeep
- Remove Other members section
    Move Tianyi to former members

Former Members
- Remove Affiliation

![image](https://user-images.githubusercontent.com/25825266/215189719-816ac154-efec-450c-804f-49abfd9b9be6.png)

The text will have to change as you have added above. We can discuss what to put in. Also I will provide you with a list of Affliations of GlyGen Members

**Comment by sujeetvkulkarni** [comment]
Rene, Robel - Co-Investigator

**Comment by sujeetvkulkarni** [comment]
Tool Development and Data Integration - Software Development and Data Integration.
Glycan Array Database Partners - Former

**Comment by sujeetvkulkarni** [comment]
efc637d4b969216f74dcf714824b80216efde487

**Comment by sujeetvkulkarni** [comment]
a629902ad869401eae0e34409184ae986430588a
