### ISSUE TITLE
Can we change CORS policy for pdb files hosted on https://data.glygen.org

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#198]
'https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Currently it is blocking me to download the file from localhost.

**Comment by rykahsay** [comment]
Can you try accessing same file from tst server (https://data.tst.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb) using GET?

**Comment by sujeetvkulkarni** [comment]
GET from a different domain fails,

Failed to download data. Possible reasons: Resource is not available, or CORS is not allowed on the server.

GET https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb net::ERR_FAILED 200 (OK)

Network tab: 
Request URL: https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb
Request Method: GET
Status Code: 200 OK
Referrer Policy: strict-origin-when-cross-origin

**Comment by rykahsay** [comment]
I don't know how to reproduce the issue you are facing --

**Comment by sujeetvkulkarni** [comment]
File from rcsb works and it has below response headers,
Request URL: https://files.rcsb.org/view/4wrn.pdb

Response Headers
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept-Encoding
Access-Control-Allow-Methods: GET, HEAD, DNT
Access-Control-Allow-Origin: *
Cache-Control: must-revalidate, post-check=0, pre-check=0
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 652178
Content-Type: text/plain;charset=UTF-8
Date: Fri, 10 Feb 2023 18:46:55 GMT
Expires: 0
Keep-Alive: timeout=5, max=100
Pragma: public
Server: Apache/2.4.41 (Ubuntu)

And below file from glygen does not work
https://data.glygen.org/ln2downloads/glycam_3d/glycan/current/G17689DH.pdb

Response Headers:
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Length: 24983
Content-Type: application/x-pilot
Date: Fri, 10 Feb 2023 18:49:53 GMT
ETag: "635b07a5-6197"
Keep-Alive: timeout=5, max=100
Last-Modified: Thu, 27 Oct 2022 22:35:17 GMT
Server: nginx/1.21.0

Please check if you need to set some header properties.

Also, you can go to https://molstar.org/viewer/ and try to load above two files using the url (specify it in the "Download Structure" option), then glygen file fails but rcsb file loads.

**Comment by rykahsay** [comment]
Please use the new /glycan/pdb/<>/ API (https://api.tst.glygen.org/glycan/pdb/G17689DH/)



<img width="770" alt="image" src="https://user-images.githubusercontent.com/20584876/222525569-a66d2093-2922-4fed-a0cf-1f39106c6031.png">

**Comment by sujeetvkulkarni** [comment]
efc637d4b969216f74dcf714824b80216efde487
