### ISSUE TITLE
Test the new N-Glycan restrictions on GNOme

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#32]
Nathan would like us to check the new restrictions on GNOme and provide him feedback.

* [Sandbox NGlycans (and ancestors)](https://raw.githack.com/glygen-glycan-data/GNOme/Branch_AddNGlycanRestriction/restrictions/GlycoTree_Nglycans.StructureBrowser.html) 
* [Sandbox OGlycans (and ancestors)](https://raw.githack.com/glygen-glycan-data/GNOme/Branch_AddNGlycanRestriction/restrictions/GlycoTree_Oglycans.StructureBrowser.html)
* [GlyTouCans that align to GlycoMotif N-glyan core motif](https://raw.githack.com/glygen-glycan-data/GNOme/Branch_AddNGlycanRestriction/restrictions/Nglycans.StructureBrowser.html)

Please have a look:
* @jeet-vora 
* @kmartinez834 
* @rajamazumder
* @mtiemeyer0919

**Comment by edwardsnj** [comment]
We have updated these links (I updated the meeting notes, but didn't realize they were already here). 

You can find a complete list here:

  https://gnome.glyomics.org/#restrictions

* GlyGen N-linked structures: https://gnome.glyomics.org/restrictions/GlyGen_NGlycans.StructureBrowser.html
* GlyGen O-linked structures: https://gnome.glyomics.org/restrictions/GlyGen_OGlycans.StructureBrowser.html
* Sandbox N-linked structures: https://gnome.glyomics.org/restrictions/GlycoTree_NGlycans.StructureBrowser.html
* Sandbox O-linked structures: https://gnome.glyomics.org/restrictions/GlycoTree_OGlycans.StructureBrowser.html

Sorry about that!

**Comment by ReneRanzinger** [comment]
This ticket is more for @mtiemeyer0919 and @rajamazumder  than for us. They need to decide which of the Gnome subsets we expose to the user. 

My suggestions is: find good labels and expose all of them and let the user choose. Downside is that it may be confusing. But even if we only choose two versions its the same level of confusion - so might as well show all.

**Comment by kmartinez834** [comment]
@edwardsnj both GlyGen O-linked and Sandbox O-linked structure browsers are blank when I click on the links above.  Is this a bug or are you still working on it?

![image](https://user-images.githubusercontent.com/90285371/219707740-4d123c19-2ca8-4039-89e3-19009a7b6e24.png)

**Comment by edwardsnj** [comment]
This is correct and working as intended. There is no single common monosaccharide composition in all structures in the restriction, so there isn’t a good initial starting composition (as with N-linked). This behavior is the same as the general GlyGen browser and the general browser. Deep linking from specific pages will go to the relevant place for all browsers.

**Comment by kmartinez834** [comment]
@edwardsnj got it, thanks for the clarification.  I was expecting to see all possible O-linked starting points, but I see why this is not possible due to uncommon starting composition.

**Comment by ReneRanzinger** [comment]
That was implemented in 2.0
