### ISSUE TITLE
Accession replaced by two other accessions

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#44]
<html><body>
<p data-renderer-start-pos="1">Robel and Rupali,<br><br></p><p data-renderer-start-pos="21"><br><br></p><p data-renderer-start-pos="24">I want to draw your attention that as there can be many old accessions that can be replaced by one accession there is also a possibility that one old accession can be replaced by two current accessions. See example below.</p><p data-renderer-start-pos="247"><br><br></p><p data-renderer-start-pos="250">Q13065 is an old accession replaced by P0DSO3 and P0DTW1 which are the current accession. However, the API shows only one of the current accession instead of two.</p><p data-renderer-start-pos="414"><br><br></p><p data-renderer-start-pos="417">Dataset -</p><div class="pm-table-container " data-layout="default" style="width: inherit;"><div class="pm-table-wrapper">

Q13065 | P0DTW1
-- | --
Q13065 | P0DSO3

</div></div><p data-renderer-start-pos="474"><br><br></p><p data-renderer-start-pos="477">API<br><br></p><p data-renderer-start-pos="483"><br><br></p><div class="code-block  css-g7s89h" style=""><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;"></code></span></div><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;"><span class="">{
</span></code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">  "reason": [
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">    {
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">      "timestamp": "2019-04-25 00:00:00", 
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">      "type": "added", 
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">      "description": "introduced in data release 1.0.13"
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">    }, 
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">    {
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">      "timestamp": "2021-02-10 00:00:00", 
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">      "replacement_id": "P0DTW1-1", 
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">      "type": "replaced", 
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">      "description": "replaced by P0DTW1-1 in data release current"
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">    }
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">  ], 
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">  "error_list": [
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">    {
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">      "error_code": "non-existent-record"
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">    }
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">  ]
</code></span><span data-code-lang="" data-ds--code--code-block="" class="prismjs css-1yzxpbn"><code style="white-space: pre;">}</code></span>
</body>
</html>

**Comment by sujeetvkulkarni** [comment]
Related to,
https://github.com/glygener/glygen-frontend/issues/151

**Comment by jeet-vora** [comment]
https://github.com/glygener/glygen-frontend/issues/205#issue-1594176843

**Comment by sujeetvkulkarni** [comment]
730ff2e2312f6d850c73b9870d359691b46c570a

**Comment by sujeetvkulkarni** [comment]
ce750fd9748fc52688016cc268f3097f60d20ff6

**Comment by sujeetvkulkarni** [comment]
c026df77e1e0a5bf56f61e7dda489c50c80004b3
