### ISSUE TITLE
For glycosylation section, can we show the fully defined or partially defined glycans first and then compositions

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#57]
For glycosylation section, can we show the fully defined or partially defined glycans first and then compositions? For eg for P00533, Asn 56 as both fully defined and composition glycans. Raja is also suggesting similar. We can discuss more about it. in one of the meetings. jkv

https://app.pageproofer.com/to/note/208826

**Comment by jeet-vora** [comment]
@ReneRanzinger to talk with Robel to add a filter option to filter by fully defined glycan.
