### ISSUE TITLE
Matrix DB calls the GAG structure as Chondroitin Sulfate A

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#61]
Matrix DB calls the GAG structure as Chondroitin Sulfate A. I think we should also include name on the protein as well as on the glycan page. Users won't know what and why are we showing the structure. jkv

https://app.pageproofer.com/to/note/187559

**Comment by jeet-vora** [comment]
Explore with Nathan to get MatrixDB names into GlyGen

**Comment by kmartinez834** [comment]
@jeet-vora @ReneRanzinger We are using names from MatrixDB for xref ID.  Will follow up with Nathan to add to names file.

https://api.glygen.org//glycan/detail//G19059PI
"crossref": [
{
      "url": "http://matrixdb.univ-lyon1.fr/cgi-bin/current/newPort?type=biomolecule&value=GAG_4", 
      "id": "GAG_4", 
      "database": "MatrixDB"
}]

"interactions": [
    {
      "interactor_name": "Superoxide dismutase [Cu-Zn]", 
      "interactor_type": "protein", 
      "interactor_id": "P00441-1", 
      "evidence": [
        {
          "url": "http://matrixdb.univ-lyon1.fr/cgi-bin/current/newPort?type=biomolecule&value=GAG_4", 
          "id": "GAG_4", 
          "database": "MatrixDB"
        },

**Comment by ReneRanzinger** [comment]
@kmartinez834 GAG_4 is not the name Jeet is looking for. Its an ID. He is looking for: 
```
Official name:
    Chondroitin Sulfate A
Other name(s):
    Chondroitin 4-sulfate
```

**Comment by kmartinez834** [comment]
Nathan is getting MatrixDB IDs from GlyTouCan.  Started a new ticket to document development of glycan semantic name pipeline https://github.com/glygener/glygen-issues/issues/41
