### ISSUE TITLE
Implement glycan list export into different formats

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#71]
New options for the download menu (Byonic and GRITS Toolbox).

API changes: GW-1507

Sujeet Kulkarni 
August 23, 2021 at 11:10 AM
Edited

Github : 75fdfa1eab31525dad893f0b484e3e30600d11e7,857f6bda4aac7e85b8cf8e732d48279d32747c4c, 502a029097423f6ee39f40bbeb67ad817c025206,ba9a078426edda9ca73aebca8a6b5ac665903508

**Comment by sujeetvkulkarni** [comment]
Byonic done.

**Comment by ReneRanzinger** [comment]
There is an open tasks for this.
