### ISSUE TITLE
Will it be nice to have a static view of all the annotation for that protein below the dynamic site annotation jeet

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#76]
Description

Note:

Will it be nice to have a static view of all the annotation for that protein below the dynamic site annotation
jeet

https://app.pageproofer.com/to/note/147193
Reported by: myGlyGen@gmail.com

Window Size: 1920 x 901
Screen Size: 1920 x 1080
Browser: Firefox version: 66.0
Platform: Windows version: 10.0

**Comment by ReneRanzinger** [comment]
@jeet-vora Do you remember what his was about. Is that still an open request?
