### ISSUE TITLE
The list page should have check box to select entries of interest. It woould also help when basket ot cart is develloped. The page should also have some filters on left to offer better selection jkv

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#78]
Description

Note:

The list page should have check box to select entries of interest. It woould also help when basket ot cart is develloped.
The page should also have some filters on left to offer better selection
jkv

https://app.pageproofer.com/to/note/166229
Reported by: myGlyGen@gmail.com

Window Size: 1366 x 632
Screen Size: 1366 x 768
Browser: Firefox version: 75.0
Platform: Windows version: 10.0

**Comment by ReneRanzinger** [comment]
Partially done. Partially in work.
