### ISSUE TITLE
Remove hyperlink? Bioportal does not have &quot;o-fucose class&quot;

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#91]
Description

Note:

Remove hyperlink? Bioportal does not have &quot;o-fucose class&quot;

https://app.pageproofer.com/to/note/185165
Reported by: myGlyGen@gmail.com

Window Size: 1691 x 935
Screen Size: 3840 x 1080
Device: WebKit
Browser: Chrome version: 79.0.3945.79
Platform: Windows version: 10.0

**Comment by ReneRanzinger** [comment]
This is already done.
