### ISSUE TITLE
Containerization of backend API and MongoDB

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#98]

**Comment by kmartinez834** [comment]
Completed by @rykahsay 

Close this ticket if acceptable

**Comment by kmartinez834** [comment]
@rykahsay see Rene's comment above - please add links to the location of the docker files or docker compose files.

**Comment by rykahsay** [comment]
@ReneRanzinger ... Dockerfile and requirements are in https://github.com/glygener/glygen-backend-api. The README.md has all the instructions required on how to deploy the API module in any linux server.

**Comment by ReneRanzinger** [comment]
@rykahsay is there a reason to use the python scripts rather than a docker compose file? We are also exposing passwords over GitHub is that a security concern or do they get changed when starting the container?

**Comment by ReneRanzinger** [comment]
@rykahsay We should remove passwords and user information from the docker files. They can be used from environment variables or from .env (environment files).
